get:
  operationId: getAllRoutes
  tags:
   - routes
  description: |
    Gets `Route` objects.
  responses:
    200:
      description: Successful response
      schema:
        $ref: "#/definitions/RoutesResponse"
post:
  operationId: createRoute
  tags:
   - routes
  description: |
    Gets `Route` objects.
  consumes:
    - application/json
  parameters:
    - name: route
      in: body
      required: true
      schema:
        "$ref": "#/definitions/Route"
  responses:
    200:
      description: Successful response
      schema:
        $ref: '#/definitions/RouteResponse'