swagger: '2.0'

info:
  version: "1.5.0"
  title: Carusto API
  description: |
    A list of APIs to work with Carusto VoIP System

host: local.carusto.com
schemes:
  - http
  - https

basePath: /api

consumes:
  - application/x-www-form-urlencoded

produces:
  - application/json

securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`

paths:
  $ref: ./paths/index.yaml

parameters:
  $ref: ./parameters/index.yaml

definitions:
  $ref: ./definitions/index.yaml
