swagger: '2.0'

info:
  version: "2.0.1"
  title: Carusto REST API
  x-logo:
    url: "./carusto.png"
  description: |
    A list of APIs to work with Carusto VoIP System

host: local.carusto.com
schemes:
  - http
  - https

basePath: /api

consumes:
  - application/x-www-form-urlencoded

produces:
  - application/json

securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
  apiKey:
    type: apiKey
    description: Authorization using API key
    name: x-auth
    in: query

security:
   - apiKey: []
   - basicAuth: []

paths:
  $ref: ./paths/index.yaml

parameters:
  $ref: ./parameters/index.yaml

definitions:
  $ref: ./definitions/index.yaml
