swagger: '2.0'

info:
  version: "1.5.0"
  title: Snippets
  description: |
    A list of APIs to manipulate Snippets that could be included in Rules and Triggers.

host: local.carusto.com
basePath: /api
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
  
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`

paths:
  /snippets:
    get:
      security:
       - basicAuth: []
      description: |
        Gets `Snippet` objects.
      responses:
        200:
          description: Successful response
          schema:
            type: array
            items:
              $ref: "#/definitions/Snippet"
    post:
      security:
       - basicAuth: []
      description: |
        Gets `Snippet` objects.
      parameters:
        - $ref: "#/parameters/snippetName"
        - $ref: "#/parameters/snippetApplications"
        - $ref: "#/parameters/snippetArguments"
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Snippet'
  /snippets/{id}:
    put:
      security:
       - basicAuth: []
      description: |
        Gets `Snippet` objects.
      parameters:
        - $ref: "#/parameters/snippetId"
        - $ref: "#/parameters/snippetName"
        - $ref: "#/parameters/snippetApplications"
        - $ref: "#/parameters/snippetArguments"
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Snippet'
    delete:
      security:
       - basicAuth: []
      description: |
        Gets `Snippet` objects.
      parameters:
        - $ref: "#/parameters/snippetId"
      responses:
        200:
          description: Successful response
parameters:

definitions:
  Snippet:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      applications:
        type: string
        items:
          $ref: "#/definitions/SnippetApplication"
      arguments:
        type: array
        items:
          $ref: "#/definitions/SnippetArgument"
  SnippetApplication:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      data:
        type: object
      children:
        type: array
        items:
          $ref: "#/definitions/SnippetApplication"
  SnippetArgument:
    type: object
    properties:
      id: 
        type: string
      name: 
        type: string
      type: 
        type: string
        enum: 
        - USER
        - GROUP
        - GATEWAY
        - CHANNEL
        - TIME
        - TEXT
        - NUMBER
