swagger: '2.0'

info:
  version: "1.5.0"
  title: Snippets
  description: |
    A list of APIs to manipulate Snippets that could be included in Rules and Triggers.

host: local.carusto.com
basePath: /api
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
  
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`

paths:

parameters:

definitions:


