type: object
properties:
  dial:
    type: object
    additionalProperties:
      type: string
  codecs:
    type: object
    additionalProperties:
      type: string
  variables:
    type: object
    additionalProperties:
      type: string
  parameters:
    type: object
    additionalProperties:
      type: object